repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-ast
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.25.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]